### PR TITLE
Feature/telegram split long messages

### PR DESCRIPTION
**Pull request by phillipadsmith**
@mrkno Can you take a look at this and let me know if you can think of a better / more sensible / less insane way to do this? I was looking at these two implementations of similar / the same problem:

https://github.com/concierge/Kassy/blob/master/core/core_integrations/messenger.js#L97

https://github.com/lukefx/hubot-telegram/blob/d0bc8c115d269a2fb6f292121a163012f1e29fb7/src/telegram.coffee#L90

### CODE REVIEW

**Comment by mrkno** [comment]
If the intent of splitting the messages is to get them delivered in order (as opposed to the problem with messenger where it simply will not accept long messages) could you not wait in some way for it to acknowledge that the message has been received? I think slack has a message queue like that somewhere but you would have to ask @Awarua-

**Comment by phillipadsmith** [comment]
@mrkno It is, indeed, because Telegram will not accept long messages: "Current maximum length is 4096 UTF8 characters" https://core.telegram.org/method/messages.sendMessage

**Comment by phillipadsmith** [comment]
They do deliver in order, otherwise; it's only in this odd scenario where the message is split into parts where the out-of-order issue happens... :-/

**Comment by mrkno** [comment]
@phillipadsmith in that case I would perdonally take the approach I did in messenger. It splits it if it is too long and tries to keep words together.

**Comment by mrkno** [comment]
@phillipadsmith once you have finalised your approach and fixed the merge conflicts remove the WIP tag and I will look at it again

**Comment by phillipadsmith** [comment]
> once you have finalised your approach and fixed the merge conflicts remove the WIP tag and I will look at it again 

👍 

I'll drop in the approach you've used for Messenger and update the PR (and remove the tag).

**Comment by phillipadsmith** [comment]
@mrkno So, looking at what you've done with the sentanceSplitter in Messenger, that's not going to work for Telegram because the size is so much longer, e.g., 4096 vs. 320. So, splitting on sentences doesn't make much sense unless I'm going to try to put them back together to get as close as possible to 4096. Otherwise, they **definitely** deliver out of order.

Going to need to give this another think. Might put this on the back burner for now in favour of adding support for sendImage and so on...

**Comment by mrkno** [comment]
@phillipadsmith No problem. I'll just leave this here until you finish it. It would be good to have support for as many of the other API's as can be supported.

**Comment by Awarua-** [comment]
@phillipadsmith take a look at the implementation that I have for the same problem for discord. In theory you should be able to use very similar code and just change the max char length const. #200

**Comment by mrkno** [comment]
@phillipadsmith did you ever get any further with this problem?

**Comment by phillipadsmith** [comment]
> @phillipadsmith did you ever get any further with this problem?

@mrkno I got sidetracked unfortunately. However, based on [this issue thread](https://github.com/yagop/node-telegram-bot-api/issues/165), I believe I need to come up with a better workaround, possibly using a queue of some sort.

I'll figure out the best place to implement, either in the node-telegram-bot-api library, or in the Telegram module for Concierge this week / weekend and send another pull request.

Let me know if you have any questions / suggestions.

**Comment by mrkno** [comment]
@phillipadsmith no problem - I won't be able to make significant progress on anything until at least Tuesday. Within `shim` there is now a generic built in function for segmenting messages which could be useful.

**Comment by phillipadsmith** [comment]
This has been resolved in [this commit](https://github.com/concierge/telegram/commit/65921e75378ba39a09e873d3eb12e139450961cd)

**Pull request closed without merging**
