### PR TITLE
Add some missing hubot api calls

### PR DESCRIPTION
**Pull request by mrkno**
- `messageRoom` in local and global context
- `reply` in a global context
- `load` in a global context

### CODE REVIEW

**Comment by Awarua-** [comment]
Approved

**Comment by p0358** [comment]
#204 Seems like it causes problems when `robot.messageRoom` gets triggered too early
```
Robot.prototype.messageRoom = function (room, messages) {
    let apis = this.platform.getIntegrationApis(); // this is undefined
    for (let api of apis) { // ...so this causes error
         try { // we have no way of working out which integration this room is on...
            for (let msg of messages) {
                api.sendMessage(msg, room);
            }
        }
        catch (e) {
            continue; // hope an exception is thrown for an invalid room...
        }
    }
};
```
However, I got same error when module triggered `robot.messageRoom` even after integrations were ready - example part of log here: http://pastebin.com/XAeykXTx
Other modules seems to work fine. Fixing this could require either making Concierge load integrations before modules or at least checking if `let apis = this.platform.getIntegrationApis();` is undefined or not to prevent errors in console and/or some caching in second case, so message could be sent as soon as integrations are ready - these are just my ideas.

**Comment by mrkno** [comment]
The problem described should now be fixed, please re-try with current version of this branch.

**Comment by p0358** [comment]
Okay, so it works, no errors at all (maybe because of that try..catch...), but if a module tries to send message quickly after its load, it's not being sent. Same with my Concierge module, seems like exports.platform.getIntegrationApis() returns null if called too quickly.

> I think loading integrations before modules wouldn't be stupid idea. Are there any drawbacks of that?

**Comment by mrkno** [comment]
> Okay, so it works, no errors at all (maybe because of that try..catch...),

Excellent, pleased it works to the point of not crashing at least.

> but if a module tries to send message quickly after its load, it's not being sent. Same with my Concierge module, seems like exports.platform.getIntegrationApis() returns null if called too quickly.

If you are getting `null` then its a bug in node.js cause the code should at least return an object regardless of anything else.... As for the load order/missed messages problem there is no way to fix this without significant redesign of a large portion of the code. As the process is asynchronous, we don't know when integrations have loaded and when modules have loaded (only when they start to load) and we cannot queue because we don't know when to drain the queue. Slack can queue because it has knowledge of when it can drain, we do not know.

Hubot avoids this problem because it only has a single integration/adapter to deal with and for the most part is not flexible in its loading process. If you absolutely need to catch the earlier messages I suggest using a setTimeout or some kind of command to initiate the process. I doubt there is a solution for fixing hubot scripts that do this within Concierge itself.

**Pull request merged**
